export const LOCALES: Record<"pl" | "ru" | "en", Record<string, string>> = {
    pl: {
        code: "pl-PL",
        tokens: "tokenów",
        title: "Raport potwierdzający otrzymanie środków (Solana)",
        signatureInput:
            "Link do transakcji (Solscan / Explorer / SolanaFM) lub hash (signature)",
        validTxLink: "Wprowadź poprawny link do transakcji lub hash (signature).",
        noTxOrRPC: "Transakcja nie istnieje czy RPC niedosępny",
        rpcError: "Błąd zapytania RPC",
        noMetadata: "Transakcja nie ma matedata (meta=null)",
        sigPlaceholder: "np. https://solscan.io/tx/… lub D8x… (signature)",
        recipient: "Twój portfel (odbiorca) — opcjonalnie, zwiększa dokładność",
        recipientPlaceholder: "np. 4Nd1…",
        invoice: "Numer faktury (opcjonalnie)",
        invoicePlaceholder: "FV-2025/09-001",
        description: "Opis / przeznaczenie płatności (do raportu)",
        descriptionPlaceholder: "Płatność za fakturę FV-…",
        fetchBtn: "Pobierz dane",
        previewBtn: "Podgląd PDF",
        downloadBtn: "Pobierz PDF",
        hint: "Wklej link do Solscan / Explorer / SolanaFM albo sam hash transakcji. Dla precyzji podaj swój adres odbiorcy.",
        docTitle: "RAPORT POTWIERDZAJĄCY OTRZYMANIE ŚRODKÓW",
        network: "Sieć blockchain",
        documentInfo: "INFORMACJE O DOKUMENCIE",
        dateCreated: "Data sporządzenia",
        docNumber: "Numer dokumentu",
        system: "System",
        txDetails: "SZCZEGÓŁY TRANSAKCJI",
        dateTime: "Data i czas",
        slot: "Slot",
        txId: "ID transakcji",
        recipientWallet: "Portfel odbiorcy",
        senderWallet: "Portfel nadawcy",
        fee: "Opłata sieciowa",
        received: "OTRZYMANE ŚRODKI",
        assetType: "Typ aktywów",
        mint: "Mint Address",
        amount: "Ilość",
        decimals: "Precyzja (decimals)",
        amountReceived: "Kwota otrzymana",
        invoiceInfo: "INFORMACJE O FAKTURZE",
        invoiceNumber: "Numer faktury",
        paymentDesc: "Opis płatności",
        techDetails: "DANE TECHNICZNE",
        explorerUrl: "Otwórz w przeglądarce",
        blockchain: "Blockchain",
        protocol: "Protokół",
        declarationTitle: "OŚWIADCZENIE",
        declaration:
            "Niniejszy dokument jest automatycznie wygenerowanym potwierdzeniem wpływu środków na wskazany portfel w sieci Solana. Dane pochodzą z publicznego łańcucha bloków (JSON-RPC).",
        footerGenerated: "Dokument wygenerowany",
        footerSystem: "System: Solana Transaction Reporter",
        closePreview: "Zamknij podgląd",
    },
    ru: {
        code: 'ru-Ru',
        tokens: "токенов",
        title: "Рапорт о получении средств (Solana)",
        signatureInput:
            "Ссылка на транзакцию (Solscan / Explorer / SolanaFM) или хэш (signature)",
        validTxLink: "Введите корректную ссылку на транзакцию или хэш (signature).",
        noTxOrRPC: "Транзакция не найдена или RPC недоступен",
        noMetadata: "Нет метаданных по транзакции (meta=null)",
        rpcError: "Ошибка запроса к RPC",
        sigPlaceholder: "например: https://solscan.io/tx/… или D8x… (signature)",
        recipient: "Ваш кошелёк (получатель) — необязательное, повышает точность",
        recipientPlaceholder: "например: 4Nd1…",
        invoice: "Номер фактуры (опционально)",
        invoicePlaceholder: "FV-2025/09-001",
        description: "Описание / назначение платежа (для рапорта)",
        descriptionPlaceholder: "Płatność за fakturę FV-…",
        fetchBtn: "Получить данные",
        previewBtn: "Предпросмотр PDF",
        downloadBtn: "Скачать PDF",
        hint: "Подсказка: можно вставить либо ссылку на Solscan / Explorer / SolanaFM, либо сам хэш транзакции (signature). Для более точного определения получателя укажите ваш адрес кошелька.",
        docTitle: "РАПОРТ О ПОЛУЧЕНИИ СРЕДСТВ",
        network: "Сеть blockchain",
        documentInfo: "ИНФОРМАЦИЯ О ДОКУМЕНТЕ",
        dateCreated: "Дата составления",
        docNumber: "Номер документа",
        system: "Система",
        txDetails: "ДЕТАЛИ ТРАНЗАКЦИИ",
        dateTime: "Дата и время",
        slot: "Slot",
        txId: "ID транзакции",
        recipientWallet: "Портфель получателя",
        senderWallet: "Портфель отправителя",
        fee: "Сетевой сбор",
        received: "ПОЛУЧЕННЫЕ СРЕДСТВА",
        assetType: "Тип актива",
        mint: "Mint Address",
        amount: "Количество",
        decimals: "Точность (decimals)",
        amountReceived: "Полученная сумма",
        invoiceInfo: "ИНФОРМАЦИЯ О СЧЕТЕ",
        invoiceNumber: "Номер счета",
        paymentDesc: "Описание платежа",
        techDetails: "ТЕХНИЧЕСКИЕ ДАННЫЕ",
        explorerUrl: "Открыть в обозревателе",
        blockchain: "Blockchain",
        protocol: "Протокол",
        declarationTitle: "ЗАЯВЛЕНИЕ",
        declaration:
            "Данный документ автоматически сгенерирован и подтверждает поступление средств на указанный кошелёк в сети Solana. Данные получены из публичного блокчейна (JSON-RPC).",
        footerGenerated: "Документ сгенерирован",
        footerSystem: "Система: Solana Transaction Reporter",
        closePreview: "Закрыть предпросмотр",
    },
    en: {
        code: "en-US",
        tokens: "tokens",
        title: "Receipt Report (Solana)",
        signatureInput:
            "Transaction link (Solscan / Explorer / SolanaFM) or hash (signature)",
        validTxLink: "Enter a valid transaction link or hash (signature).",
        noTxOrRPC: "Transaction was not found or RPC unavaliable",
        noMetadata: "Transaction has no matedata (meta=null)",
        rpcError: "Error request to RPC",
        sigPlaceholder: "e.g. https://solscan.io/tx/… or D8x… (signature)",
        recipient: "Your wallet (recipient) — optional, improves accuracy",
        recipientPlaceholder: "e.g. 4Nd1…",
        invoice: "Invoice number (optional)",
        invoicePlaceholder: "INV-2025/09-001",
        description: "Description / payment purpose (for the report)",
        descriptionPlaceholder: "Payment for invoice INV-…",
        fetchBtn: "Fetch data",
        previewBtn: "Preview PDF",
        downloadBtn: "Download PDF",
        hint: "Tip: paste a Solscan / Explorer / SolanaFM link or the transaction hash. For better accuracy, provide your recipient wallet address.",
        docTitle: "RECEIPT REPORT",
        network: "Blockchain network",
        documentInfo: "DOCUMENT INFORMATION",
        dateCreated: "Date created",
        docNumber: "Document number",
        system: "System",
        txDetails: "TRANSACTION DETAILS",
        dateTime: "Date & time",
        slot: "Slot",
        txId: "Transaction ID",
        recipientWallet: "Recipient wallet",
        senderWallet: "Sender wallet",
        fee: "Network fee",
        received: "RECEIVED FUNDS",
        assetType: "Asset type",
        mint: "Mint Address",
        amount: "Amount",
        decimals: "Precision (decimals)",
        amountReceived: "Amount received",
        invoiceInfo: "INVOICE INFORMATION",
        invoiceNumber: "Invoice number",
        paymentDesc: "Payment description",
        techDetails: "TECHNICAL DETAILS",
        explorerUrl: "Open in explorer",
        blockchain: "Blockchain",
        protocol: "Protocol",
        declarationTitle: "DECLARATION",
        declaration:
            "This document is an automatically generated confirmation of funds received to the specified wallet on the Solana network. Data comes from the public blockchain (JSON-RPC).",
        footerGenerated: "Document generated",
        footerSystem: "System: Solana Transaction Reporter",
        closePreview: "Close preview",
    },
};
